sudo: required
services:
  - docker
before_install:
  - docker build -t jjino/4times:v1.8 .
script:
  - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
  - docker push jjino/4times:v1.8
notifications:
  email:
    recipients:
      - jinojoe@gmail.com
      - jjino@protonmail.com
    on_success: always
    on_failure: always
