sudo: required
services:
  - docker
before_install:
  - docker build -t jjino/test:latest .
script:
  - docker run --rm jjino/test:latest vim --version
  - docker ps -a
notifications:
  email:
    - jinojoe@gmail.com
    - jjino@protonmail.com
