sudo: required
services:
  - docker
before_install:
  - docker build -t "$docker_username"/4times:v1.5 .
script:
  - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
  - docker push jjino/4times:v1.5
notifications:
  email:
    recipients:
      - jinojoe@gmail.com
      - jjino@protonmail.com
    on_success: never
    on_failure: always
