sudo: required
services:
  - docker
before_install:
  - docker build -t jjino/4times:latest .
script:
  - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
  - docker push
notifications:
  email:
    - jinojoe@gmail.com
    - jjino@protonmail.com
