sudo: required
services:
  - docker
before_install:
  - docker build -t "$docker_username"/4times:v1.6 .
script:
  - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
	-	docer images
  - docker push "$docker_username"/4times:v1.6
notifications:
  email:
    recipients:
      - jinojoe@gmail.com
      - jjino@protonmail.com
    on_success: always
    on_failure: always
    template:
      - "%{repository_slug} (%{commit}) : %{message}"
      - "Build details: %{build_url}"
