env:
  global:
    - password: "56apple91$"
    - username: "jjino"
sudo: required
services:
  - docker
before_install:
  - docker build -t jjino/4times:v1.9 .
script:
  - echo "password" | docker login -u "username" --password-stdin
    #- echo "$docker_password" | docker login -u "$docker_username" --password-stdin
  - docker push jjino/4times:v1.9
  - docker ps -a
notifications:
  email:
    recipients:
      - jinojoe@gmail.com
      - jjino@protonmail.com
    on_success: always
    on_failure: always
